// scripts/build-css.mjs
import fs from "node:fs/promises";
import path from "node:path";
import fg from "fast-glob";
import chokidar from "chokidar";

const ROOT = process.cwd();
const OUTFILE = path.join(ROOT, "styles.css"); // Obsidian reads THIS file

// Your editable CSS lives here:
const BASE = "css/styles";

// Build order: put a common file first if you have it, then components, then everything else
const PATTERNS_ORDERED = [
  `${BASE}/common.css`,
  `${BASE}/components/**/*.css`,
  `${BASE}/**/*.css`
];

const IGNORE = ["**/node_modules/**", "**/.obsidian/**", "**/dist/**"];

async function buildOnce() {
  const chunks = [];
  const seen = new Set();

  for (const pat of PATTERNS_ORDERED) {
    const files = await fg(pat, {
      cwd: ROOT,
      dot: false,
      onlyFiles: true,
      unique: true,
      ignore: IGNORE
    });
    for (const f of files) {
      if (seen.has(f)) continue;
      seen.add(f);
      const abs = path.join(ROOT, f);
      try {
        const css = await fs.readFile(abs, "utf8");
        chunks.push(`/* --- ${f} --- */\n${css.trim()}\n`);
      } catch (e) {
        console.error("[build-css] Failed to read", f, e);
      }
    }
  }

  const header = `/* ===== Generated by build-css.mjs at ${new Date().toISOString()} ===== */\n\n`;
  const out = header + chunks.join("\n");
  await fs.writeFile(OUTFILE, out, "utf8");
  console.log(`[build-css] Wrote ${OUTFILE} (${out.length} bytes)`);
}

async function main() {
  const WATCH = process.argv.includes("--watch");
  await buildOnce();

  if (WATCH) {
    console.log(`[build-css] Watching ${BASE}/**/*.css …`);
    const watcher = chokidar.watch(`${BASE}/**/*.css`, {
      ignoreInitial: true,
      ignored: IGNORE,
      awaitWriteFinish: { stabilityThreshold: 120, pollInterval: 20 }
    });

    const trigger = async (file) => {
      console.log(`[build-css] Change: ${file}`);
      await buildOnce();
    };

    watcher.on("add", trigger).on("change", trigger).on("unlink", trigger);
  }
}

main().catch((e) => {
  console.error("[build-css] Fatal:", e);
  process.exit(1);
});
